# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('englishWord', models.CharField(max_length=20)),
                ('chineseWord', models.CharField(max_length=20)),
            ],
        ),
    ]
