# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_pair'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
            ],
        ),
    ]
